### ISSUE TITLE
[Bug]: SwitchIlineQuery doesnt work in mini apps on IOS client 

### ISSUE THREAD

**Issue by danyarubtsov** [Telegram-Mini-Apps/telegram-apps#457]
### Telegram Application

Telegram for iOS

### Describe the Bug

At the moment, there are two critical errors in mini-applications related to inline sharing, and both of them are on the iOS client.

When we launch the application through the WebApp Button, we simply cannot use switchInlineQuery, absolutely nothing happens. Moreover, this problem was on this forum 8 months ago, but nothing happened. Link to that issue: https://bugs.telegram.org/c/36392
When we launch through a direct link (like https://t.me/jago_superbot/quiz) and select a person or channel in which we want to share our inline, instead of switching the chat to the selected one, we remain in the chat in which a mini-application was opened, for example a bot or a channel in which there was advertising. That is, selecting users for switchInlineQuery completely does not work through the web app button, and selecting a person does not work through a direct link, which is technically also considered broken functionality.
This greatly spoils the viral/referral mechanics, so I hope you can fix this quickly so that mini-applications can continue to develop correctly, finding new audiences through viral mechanics

issues: https://bugs.telegram.org/c/42296, https://github.com/TelegramMessenger/Telegram-iOS/issues/1485

### To Reproduce

Open app via web app button from ios
try to call switchInlineQuery,
Nothing happened.

### Expected Behavior

switchInlineQuery working correctly :)

**Comment by heyqbnk** [comment]
As I see, the issue in the Telegram bug report was fixed:
https://bugs.telegram.org/c/36392

**Comment by phoenix-mstu** [comment]
switchInlineQuery still doesnt work for miniapps launched by button on ios

**Comment by tenkkov** [comment]
same. Seems like switchInlineQuery does nothing on telegram ios
